FROM ubuntu:18.04

WORKDIR /tmp

RUN apt update && \
    apt install -yq --no-install-recommends \
        python3 \
        python3-pip \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install -U pip
RUN python3 -m pip install -U setuptools

RUN pip3 install \
    setuptools \
    wheel

COPY ./edge_server_client_requirements.txt .

RUN pip3 install -r edge_server_client_requirements.txt

COPY edge_server/ edge_server/

COPY setup.py .

RUN pip3 install .

RUN rm -r /tmp/*

COPY images/ images/

ENV IMAGES_PATH="/tmp/images/" \
    RUNNING_PERIOD=60 \
    RUNNING_INTERVAL=1

ENV EDGE_SERVER_IP_ADDR 0.0.0.0
ENV EDGE_SERVER_PORT 8000

ENTRYPOINT edge-server-client
