kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: edge-server-cv
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edge-server-cv
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Pods
    pods:
      #metricName: flask_http_request
      metricName: edge_server_art_for_30
      targetAverageValue: 300m

